### ISSUE TITLE
UE 5.4 errors

### ISSUE THREAD

**Issue by CodenameReality** [immutable/unreal-immutable-sdk#94]
Downloading a fresh copy of the code and running it in Visual Studio Community 2022 combined with Unreal Engine 5.4 results in the following error log, resulting in a failed compilation:

`1>[3/7] Compile [x64] Module.Immutable.cpp
1>C:\CR SVN\Projects\Mechazod\Mechazod\Plugins\Immutable\Source\Immutable\Public\Immutable\ImtblJSMessages.h(113): warning C4996: 'FJsonObject::TryGetNumberField': Passing an ANSI string to TryGetNumberField has been deprecated outside of UTF-8 mode. Please use the overload that takes a TCHAR string. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\CR SVN\Projects\Mechazod\Mechazod\Plugins\Immutable\Source\Immutable\Public\Immutable\ImtblJSMessages.h(114): warning C4996: 'FJsonObject::TryGetStringField': Passing an ANSI string to TryGetStringField has been deprecated outside of UTF-8 mode. Please use the overload that takes a TCHAR string. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\CR SVN\Projects\Mechazod\Mechazod\Plugins\Immutable\Source\Immutable\Private\Immutable\ImmutableDataTypes.cpp(20): warning C4996: 'FJsonObject::HasField': Passing an ANSI string to HasField has been deprecated outside of UTF-8 mode. Please use the overload that takes a TCHAR string. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\CR SVN\Projects\Mechazod\Mechazod\Plugins\Immutable\Source\Immutable\Private\Immutable\ImmutableDataTypes.cpp(22): warning C4996: 'FJsonObject::RemoveField': Passing an ANSI string to RemoveField has been deprecated outside of UTF-8 mode. Please use the overload that takes a TCHAR string. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\CR SVN\Projects\Mechazod\Mechazod\Plugins\Immutable\Source\Immutable\Private\Immutable\ImmutablePassport.cpp(203): error C4855: implicit capture of 'this' via '[=]' is deprecated in '/std:c++20'
1>C:\CR SVN\Projects\Mechazod\Mechazod\Plugins\Immutable\Source\Immutable\Private\Immutable\ImmutableRequests.cpp(42): warning C4996: 'FJsonObject::HasField': Passing an ANSI string to HasField has been deprecated outside of UTF-8 mode. Please use the overload that takes a TCHAR string. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\CR SVN\Projects\Mechazod\Mechazod\Plugins\Immutable\Source\Immutable\Private\Immutable\ImmutableRequests.cpp(45): warning C4996: 'FJsonObject::GetArrayField': Passing an ANSI string to GetArrayField has been deprecated outside of UTF-8 mode. Please use the overload that takes a TCHAR string. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.`

The error is related to line 203 of ImmutablePassport.cpp
`CallJS(ImmutablePassportAction::GetIdToken, TEXT(""), ResponseDelegate, FImtblJSResponseDelegate::CreateLambda([ResponseDelegate](FImtblJSResponse Response)`

Unfortunately I do not know myself how to resolve this error..

**Comment by YermekG** [comment]
Hello @CodenameReality, Thank you for reporting the issue. It was resolved in [v.1.2.7](https://github.com/immutable/unreal-immutable-sdk/releases/tag/v1.2.7)
